/*
 *  Author:         Brett Heithold
 *  File:           types.c
 *  Created:        10/21/2020
 *  Last Revised:   10/23/2020
 */


#include "../header/types.h"


/* Types */
char *INTEGER_TYPE = "INTEGER_TYPE";
char *REAL_TYPE = "REAL_TYPE";
char *STRING_TYPE = "STRING_TYPE";
char *BOOLEAN_TYPE = "BOOLEAN_TYPE";
char *ID_TYPE = "ID_TYPE";
char *VARIABLE_TYPE = "VARIABLE_TYPE";
char *NULL_TYPE = "NULL_TYPE";

/* Punctuation */
char *OPAREN = "OPAREN";
char *CPAREN = "CPAREN";
char *OBRACE = "OBRACE";
char *CBRACE = "CBRACE";
char *COMMA = "COMMA";
char *COLON = "COLON";
char *SEMICOLON = "SEMICOLON";

/* Binary Operators */
char *PLUS_BINARY = "PLUS_BINARY";
char *MINUS_BINARY = "MINUS_BINARY";
char *TIMES_BINARY = "TIMES_BINARY";
char *DIVIDE_BINARY = "DIVIDE_BINARY";
char *POW_BINARY = "POW_BINARY";
char *MODULO_BINARY = "MODULO_BINARY";
char *ASSIGN_BINARY = "ASSIGN_BINARY";
char *PLUS_ASSIGN_BINARY = "PLUS_ASSIGN_BINARY";
char *MINUS_ASSIGN_BINARY = "MINUS_ASSIGN_BINARY";
char *TIMES_ASSIGN_BINARY = "TIMES_ASSIGN_BINARY";
char *DIVIDE_ASSIGN_BINARY = "DIVIDE_ASSIGN_BINARY";
char *MOD_ASSIGN_BINARY = "MOD_ASSIGN_BINARY";
char *POW_ASSIGN_BINARY = "POW_ASSIGN_BINARY";
char *MODULO_ASSIGN_BINARY = "MODULO_ASSIGN_BINARY";
char *DOT_BINARY = "DOT_BINARY";

/* Unary Operators */
char *INCREMENT_UNARY = "INCREMENT_UNARY";
char *DECREMENT_UNARY = "DECREMENT_UNARY";
char *NEGATE_UNARY = "NEGATE_UNARY";

/* Comparators */
char *EQUALS_COMPARATOR = "EQUALS_COMPARATOR";
char *NOT_EQUALS_COMPARATOR = "NOT_EQUALS_COMPARATOR";
char *GREATER_THAN_COMPARATOR = "GREATER_THAN_COMPARATOR";
char *LESSER_THAN_COMPARATOR = "LESSER_THAN_COMPARATOR";
char *GREATER_EQUALS_COMPARATOR = "GREATER_EQUALS_COMPARATOR";
char *LESSER_EQUALS_COMPARATOR = "LESSER_EQUALS_COMPARATOR";

/* Logical Operators */
char *AND = "AND";
char *OR = "OR";
char *XOR = "XOR";

/* Keywords */
char *IF = "IF_KEYWORD";
char *ELSE = "ELSE_KEYWORD";
char *FOR = "FOR_KEYWORD";
char *WHILE = "WHILE_KEYWORD";
char *FUNCTION = "FUNCTION_KEYWORD";
char *VAR = "VAR_KEYWORD";
char *RETURN = "RETURN_KEYWORD";
char *BREAK = "BREAK_KEYWORD";
char *CONTINUE = "CONTINUE_KEYWORD";
char *CLASS = "CLASS_KEYWORD";
char *LAMBDA = "LAMBDA_KEYWORD";
char *VOID = "VOID_KEYWORD";
char *TRUE = "TRUE_KEYWORD";
char *FALSE = "FALSE_KEYWORD";

/* Other */
char *UNKNOWN = "UNKNOWN";
char *BAD_NUMBER = "BAD_NUMBER";
char *BAD_CHARACTER = "BAD_CHARACTER";
char *BAD_STRING = "BAD_STRING";
char *END_OF_INPUT = "END_OF_INPUT";
char *VARIABLE_DEFINITION = "VARIABLE_DEFINITION";
char *FUNCTION_DEFINITION = "FUNCTION_DEFINITION";
char *FUNCTION_CALL = "FUNCTION_CALL";
char *CLASS_DEFINITION = "CLASS_DEFINITION";
