/*
 *  Author:         Brett Heithold
 *  File:           types.c
 *  Created:        10/21/2020
 *  Last Revised:   11/23/2020
 */


#include "../header/types.h"


/* Types */
char *INTEGER_TYPE = "INTEGER_TYPE";
char *REAL_TYPE = "REAL_TYPE";
char *STRING_TYPE = "STRING_TYPE";
char *BOOLEAN_TYPE = "BOOLEAN_TYPE";
char *ID_TYPE = "ID_TYPE";
char *VARIABLE_TYPE = "VARIABLE_TYPE";
char *NULL_TYPE = "NULL_TYPE";

/* Punctuation */
char *OPAREN = "OPAREN";
char *CPAREN = "CPAREN";
char *OBRACE = "OBRACE";
char *CBRACE = "CBRACE";
char *OBRACKET = "OBRACKET";
char *CBRACKET = "CBRACKET";
char *COMMA = "COMMA";
char *COLON = "COLON";
char *SEMICOLON = "SEMICOLON";

/* Binary Operators */
char *BINARY_OPERATOR = "BINARY_OPERATOR";
char *PLUS_BINARY = "PLUS_BINARY";
char *MINUS_BINARY = "MINUS_BINARY";
char *TIMES_BINARY = "TIMES_BINARY";
char *DIVIDE_BINARY = "DIVIDE_BINARY";
char *POW_BINARY = "POW_BINARY";
char *MODULO_BINARY = "MODULO_BINARY";
char *ASSIGN_BINARY = "ASSIGN_BINARY";
char *PLUS_ASSIGN_BINARY = "PLUS_ASSIGN_BINARY";
char *MINUS_ASSIGN_BINARY = "MINUS_ASSIGN_BINARY";
char *TIMES_ASSIGN_BINARY = "TIMES_ASSIGN_BINARY";
char *DIVIDE_ASSIGN_BINARY = "DIVIDE_ASSIGN_BINARY";
char *POW_ASSIGN_BINARY = "POW_ASSIGN_BINARY";
char *MODULO_ASSIGN_BINARY = "MODULO_ASSIGN_BINARY";
char *DOT_BINARY = "DOT_BINARY";

/* Unary Operators */
char *UNARY_OPERATOR = "UNARY_OPERATOR";
char *INCREMENT_UNARY = "INCREMENT_UNARY";
char *DECREMENT_UNARY = "DECREMENT_UNARY";
char *NEGATE_UNARY = "NEGATE_UNARY";

/* Comparators */
char *COMPARATOR = "COMPARATOR";
char *EQUALS_COMPARATOR = "EQUALS_COMPARATOR";
char *NOT_EQUALS_COMPARATOR = "NOT_EQUALS_COMPARATOR";
char *GREATER_THAN_COMPARATOR = "GREATER_THAN_COMPARATOR";
char *LESSER_THAN_COMPARATOR = "LESSER_THAN_COMPARATOR";
char *GREATER_EQUALS_COMPARATOR = "GREATER_EQUALS_COMPARATOR";
char *LESSER_EQUALS_COMPARATOR = "LESSER_EQUALS_COMPARATOR";

/* Logical Operators */
char *LOGICAL_OPERATOR = "LOGICAL_OPERATOR";
char *AND = "AND";
char *OR = "OR";
char *XOR = "XOR";
char *NOT = "NOT";

/* Keywords */
char *IF = "IF_KEYWORD";
char *ELSE = "ELSE_KEYWORD";
char *FOR = "FOR_KEYWORD";
char *WHILE = "WHILE_KEYWORD";
char *FUNCTION = "FUNCTION_KEYWORD";
char *VAR = "VAR_KEYWORD";
char *RETURN = "RETURN_KEYWORD";
char *BREAK = "BREAK_KEYWORD";
char *CONTINUE = "CONTINUE_KEYWORD";
char *CLASS = "CLASS_KEYWORD";
char *LAMBDA = "LAMBDA_KEYWORD";
char *VOID = "VOID_KEYWORD";
char *IMPORT = "IMPORT";
char *PRINT = "PRINT";
char *PRINTLN = "PRINTLN";

/* Other */
char *UNKNOWN = "UNKNOWN";
char *BAD_NUMBER = "BAD_NUMBER";
char *BAD_CHARACTER = "BAD_CHARACTER";
char *BAD_STRING = "BAD_STRING";
char *END_OF_INPUT = "END_OF_INPUT";
char *ENVIRONMENT = "ENVIRONMENT";
char *JOIN = "JOIN";

/********** Grammar Function Types **********/
char *PROGRAM = "PROGRAM";
char *STATEMENT = "STATEMENT";
char *STATEMENT_LIST = "STATEMENT_LIST";
char *VARIABLE_DEFINITION = "VARIABLE_DEFINITION";
char *FUNCTION_DEFINITION = "FUNCTION_DEFINITION";
char *CLASS_DEFINITION = "CLASS_DEFINITION";
char *FUNCTION_CALL = "FUNCTION_CALL";
char *INHERITANCE = "INHERITANCE";
char *INIT = "INIT";
char *DIMENSION = "DIMENSION";
char *DIMENSION_LIST = "DIMENSION_LIST";
char *PARAMETER_LIST = "PARAMETER_LIST";
char *VARIABLE_EXPRESSION = "VARIABLE_EXPRESSION";
char *EXPRESSION = "EXPRESSION";
char *EXPRESSION_LIST = "EXPRESSION_LIST";
char *CONDITIONAL_EXPRESSION_LIST = "CONDITIONAL_EXPRESSION_LIST";
char *UNARY = "UNARY";
char *LAMBDA_DEFINITION = "LAMBDA_DEFINITION";
char *BLOCK = "BLOCK";
char *FOR_LOOP = "FOR_LOOP";
char *WHILE_LOOP = "WHILE_LOOP";
char *IF_STATEMENT = "IF_STATEMENT";
char *ELSE_STATEMENT = "ELSE_STATEMENT";
char *RETURN_STATEMENT = "ELSE_STATEMENT";
